= Quarkus AdminFaces Starter
:page-layout: base
:source-language: java
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:numbered:
:doctype: book
:toc: preamble
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

This project is based/depends on https://github.com/tandraschko/quarkus-myfaces[quarkus-myfaces prototype^] and shows a `responsive *JSF*` application running on https://quarkus.io/[Quarkus^]. 

NOTE: Only hotspot was tested and native mode will probably not work.
 
== How to try it?

=== Build MyFaces 

* clone https://github.com/apache/myfaces.git 
* `mvn versions:set -DnewVersion=3.0.0-M1 -DprocessAllModules` (NOTE: we need to update the version to M1 as Quarkus does _NOT_ support snapshots)
* `mvn clean install -DskipTests`

=== Build Admin Template

* `git clone https://github.com/adminfaces/admin-template.git && cd admin-template && mvn versions:set -DnewVersion=1.0.1 && mvn clean install`
   
=== Build quarkus-myfaces

* `git clone https://github.com/rmpestano/quarkus-myfaces && cd quarkus-myfaces/quarkus-myfaces && mvn clean install`

[TIP]
====

To build the quarkus extension you need to add jboss maven repository to your maven settings.xml:

----
<repositories>
    <repository>
        <id>jboss</id>
        <name>jboss repo</name>
        <url>http://repository.jboss.org/nexus/content/groups/public-jboss/</url>
    </repository>
<repositories>
<pluginRepositories>
    <pluginRepository>
        <id>jboss</id>
        <name>jboss repo</name>
        <url>http://repository.jboss.org/nexus/content/groups/public-jboss/</url>
   </pluginRepository>
</pluginRepositories>
----

====

=== Run Admin starter 

Finally run this project: 

* `mvn compile quarkus:dev`
* access http://localhost:8080/
