= Quarkus AdminFaces Starter
:page-layout: base
:source-language: java
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:numbered:
:doctype: book
:toc: preamble
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

This project depends on https://github.com/apache/myfaces/tree/master/extensions/quarkus[quarkus-myfaces^] and https://github.com/rmpestano/quarkus-omnifaces[quarkus-omnifaces^] extensions. This project shows a `responsive *JSF*` application running on https://quarkus.io/[Quarkus^].

NOTE: Only hotspot is supported.
 
== How to try it?


=== Build quarkus-omnifaces


`git clone https://github.com/rmpestano/quarkus-omnifaces && mvn clean install -DskipTests`

[TIP]
====

To build the quarkus extension you need to add jboss maven repository to your maven settings.xml:

----
<repositories>
    <repository>
        <id>jboss</id>
        <name>jboss repo</name>
        <url>https://repository.jboss.org/nexus/content/groups/public-jboss/</url>
    </repository>
</repositories>
<pluginRepositories>
    <pluginRepository>
        <id>jboss</id>
        <name>jboss repo</name>
        <url>https://repository.jboss.org/nexus/content/groups/public-jboss/</url>
   </pluginRepository>
</pluginRepositories>
----

====

=== Run Admin starter 

Finally run this project: 

* `git clone https://github.com/adminfaces/quarkus-admin-starter && cd quarkus-admin-starter && mvn compile quarkus:dev`
* access http://localhost:8080/

TIP: Run via quarkus runner with `mvn clean package && java -jar target/quarkus-admin-starter-runner.jar`

== Docker

to run via docker execute the following commands:

* `mvn clean package && docker build -f docker/Dockerfile.jvm -t quarkus/admin-starter . && docker run -i --rm -p 8080:8080 quarkus/admin-starter`

OR run already pushed image:

* `docker run -i --rm -p 8080:8080 rmpestano/quarkus-admin-starter`
